version: "3"
services:
  gofinances_postgres:
    image: postgres:11
    container_name: gofinances_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.ignore/postgres/postgres:/var/lib/postgresql/data
    networks:
      - gofinances_api
    environment:
      - POSTGRES_NAME=gofinances_db
      - POSTGRES_PASSWORD=gofinances
      - POSTGRES_USER=gofinances
      - POSTGRES_DB=gofinances_db

  gofinances_pgadmin:
    image: dpage/pgadmin4
    container_name: gofinances_pgadmin
    ports:
      - "5433:80"
    networks:
      - gofinances_api
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gofinances.com
      - PGADMIN_DEFAULT_PASSWORD=gofinances_pass
    volumes:
      - ./.ignore/var/lib/pgadmin:/var/lib/pgadmin
    logging:
      driver: none

networks:
  gofinances_api:
    driver: bridge
